spring:
  application:
    name: bee-bot-service
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: beees
    password: THREEES
    url: jdbc:postgresql://localhost:5432/beeebot_db
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 25
      idle-timeout: 300000
      connection-test-query: SELECT 1
logging:
  level:
    com.beees.*: DEBUG

bot:
  bot-username: "BeeeBot"
  command-string: "o8o "
  big-ban-role: all-ban
  poll-results-channel: "772996698196410400"
  permissions:
    manage-light-roles:
      - admin
      - moderator
      - channel-mod
      - color-captain
    manage-heavy-roles:
      - admin
      - moderator
      - channel-mod
    manage-polls:
      - admin
      - moderator
      - channel-mod
      - poll-captain

